@base_url = http://localhost:8080

POST {{base_url}}/authenticate
Content-Type: application/json

{
    "username": "john@smith.com",
    "password": "P@ssw0rd!"
}


###

POST {{base_url}}/authenticate
Content-Type: application/json

{
    "username": "sally@jones.com",
    "password": "P@ssw0rd!"
}
